### ISSUE TITLE
Speed improvement

### ISSUE THREAD

**Issue by jannisborn** [PaccMann/paccmann_chemistry#11]
Current model is super slow (every step of batch size 64 takes 2-3 sec). Identified plenty options to speed up:

- move things from forward pass to constructor, e.g. use_stack, then define lambda functions in constructor
- remove ifs in forward
- move out optimizer from stackgru to TeacherVAE 
- bidirectional GRU in constructor
- create initializers for stack and hidden in constructor and only set values in forward pass [see here](https://discuss.pytorch.org/t/keeping-constant-value-in-module-on-correct-device/10129) or [here](https://discuss.pytorch.org/t/keeping-constant-value-in-module-on-correct-device/10129).

**Comment by niladell** [comment]
On top of that I think that using PackedSequences is gonna make things faster too, I will work on that in parallel [here](https://github.com/PaccMann/paccmann_chemistry/tree/switch_to_packed_sequences) and then we can merge together down the line. I'll put a draft pull request as soon as it starts to take some proper form.

**Comment by jannisborn** [comment]
Closed by #12
