### ISSUE TITLE
Decoder breaking with batch_size=1

### ISSUE THREAD

**Issue by niladell** [PaccMann/paccmann_chemistry#13]
I think that the problem is somewhere around here. I have been trying to run the model with single samples (batch size set to 1) and it breaks due to a dimension mismatch.

I think that the problem may be around here, however I need to properly look into what may be causing it. I do recall we had a similar problem with the encoder some many commits ago.

https://github.com/PaccMann/paccmann_chemistry/blob/d18e8bbfaec5970fba1474de9d2d20219ba8905a/paccmann_chemistry/models/vae.py#L451-L453

**Comment by jannisborn** [comment]
are you reporting for `master` or `dev`?

**Comment by niladell** [comment]
For `dev`

**Comment by jannisborn** [comment]
Can you pls paste the error message here? Are you sure tour `input_token` is to 2D? If not, the stack gru will break for sure.

**Comment by niladell** [comment]
Hey, sorry for the late response

With a `sample` (passed to `latent_z`) of shape `(1, 1, 256)` I get this:
```Python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-235-ef3a9735362c> in <module>
      4 sample.shape
----> 5 mol = paccmann_vae.decode(sample)

~/Documents/IBM/paccmann/paccmann_polymer/paccmann_polymer/models/paccmann_encoder.py in decode(self, latent_z, generate_len, search)
     79                                    ).to(self.device),
     80             generate_len=generate_len,
---> 81             search=search
     82         )
     83         return next(molecule_iter)

~/Documents/IBM/paccmann/paccmann_chemistry/paccmann_chemistry/models/vae.py in generate(self, latent_z, prime_input, end_token, generate_len, search)
    639             end_token,
    640             search=search,
--> 641             generate_len=generate_len
    642         )
    643 

~/Documents/IBM/paccmann/paccmann_chemistry/paccmann_chemistry/models/vae.py in generate_from_latent(self, latent_z, prime_input, end_token, search, generate_len)
    459 
    460                 logits = self.output_layer(output).squeeze()
--> 461                 top_idx = search.step(logits)
    462 
    463                 input_token = top_idx.view(1, -1).to(self.device)

~/Documents/IBM/paccmann/paccmann_chemistry/paccmann_chemistry/utils/search.py in step(self, logits)
    133         """
    134         super().step(logits)
--> 135         probabilities = torch.softmax(logits.div(self.temperature), 1)
    136         return torch.stack(
    137             [

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

With `input_token` you mean the input of the input to the `decoder`?

I assume that some of the `.squeeze()` operations is squeezing the batch dimension at some step down the line.

**Comment by jannisborn** [comment]
Yep, the fix is probably to have in `generate_from_latent(...` at line 460:
```
logits = self.output_layer(output).squeeze(dim=1)
```

Fixed the same issue at a couple of different spots too. Briefly tested functionality of packed and padded mode with batch sizes 1 and 10. Seems stable now.

Thanks for the pointer @niladell
