### ISSUE TITLE
AttributeError: 'str' object has no attribute 'long'

### ISSUE THREAD

**Issue by cook-kuk** [PaccMann/paccmann_chemistry#15]
I got error AttributeError: 'str' object has no attribute 'long' in function packed_sequential_data_preparation. 

Input_batch in function packed_sequential_data_preparation should be torch.Tensor. But output of each batch is string when i used the dataset(chembl_22_clean_1576904_sorted_std_final.smi) that your group provided.  

I think batch data convert into tensor before batch data enter  func packed_sequential_data_preparation.

How can i fix it?

**Comment by drugilsberg** [comment]
Hey @SeunghoKuk-dev thanks a lot for trying the repo. Can you help us to reproduce the problem?
Maybe report the command you tried to run. Thanks in advance.

**Comment by cook-kuk** [comment]
Sure. 

I ran it using this command line. 

python code\paccmann_chemistry\examples\train_vae.py data\splitted_data\train_chembl_22_clean_1576904_sorted_std_final.smi data\splitted_data\test_chembl_22_clean_1576904_sorted_std_final.smi data\smiles_language_chembl_gdsc_ccle.pkl models c
ode\paccmann_chemistry\examples\example_params.json svae2

**Comment by drugilsberg** [comment]
might be related to: https://github.com/PaccMann/paccmann_rl/issues/1

**Comment by jannisborn** [comment]
Seems like this was a versioning issue which was resolved via https://github.com/PaccMann/paccmann_rl/pull/2
