### ISSUE TITLE
Pre-trained weights?

### ISSUE THREAD

**Issue by htalibart** [PaccMann/paccmann_chemistry#19]
Hi, thank you for making your code public!

Could you provide documentation on how to use parameter and pre-trained weights files in https://ibm.ent.box.com/v/paccmann-pytoda-data?

I tried the following code, using files downloaded from the "svae" folder:

```
from paccmann_chemistry.models.vae import StackGRUDecoder, StackGRUEncoder, TeacherVAE
params_path = "pretrained_models/model_params.json"
params = dict()
with open(params_path, 'r') as f:
    params.update(json.load(f))
params['batch_size'] = 1
weights_path = "pretrained_models/weights/best_loss.pt"
gru_encoder = StackGRUEncoder(params).to(device)
gru_decoder = StackGRUDecoder(params).to(device)
gru_vae = TeacherVAE(gru_encoder, gru_decoder).to(device)
gru_vae.load_state_dict(torch.load(weights_path, map_location=device))
```

and I got 
```
TypeError: Argument `mode` should be a string.
```

so I tried with the parameter file in the examples/ folder, and I also tried loading both parameter files, but I got lots of errors such as
```
RuntimeError: Error(s) in loading state_dict for TeacherVAE:
	Missing key(s) in state_dict: "encoder.embedding.weight", "decoder.embedding.weight", "decoder.output_layer.weight", "decoder.output_layer.bias".
```
and unexpected keys, which make me think that they might not be the right files, so where can we find them...?

Thanks in advance!

**Comment by jannisborn** [comment]
Hi @htalibart,

Thanks for the interest in this repo & code. I'm not sure what is exactly your objective, but if you just want to run inference on a pretrained model, I strongly recommend to use GT4SD: https://github.com/GT4SD/gt4sd-core

There's a zoo of molecular generative models there, including multiple wrappers that use the VAE in this code. A training pipeline for finetuning or training from scratch on your own data is also available there.

To run inference have a look at this demo: https://github.com/GT4SD/gt4sd-core/blob/main/notebooks/discovery-demo.ipynb
The models you need are `PaccMannVAE` and `PaccMannRLProteinBasedGenerator`. They are using the weights that you downloaded from the Box folder, they are just duplicated to our GT4SD COS and then stored in your local cache once you use the model for the first time.

If you want to train/finetune such a model, you can use the `paccmann-vae-trainer`, see this example in the README: https://github.com/GT4SD/gt4sd-core#saving-a-trained-algorithm-for-inference-via-the-cli-command

**Comment by htalibart** [comment]
Thank you for your answer!

I'm only interested in the basic usage of a pre-trained molecule autoencoder, i.e. load the model, encode a molecule, get an embedding vector, play around with this embedding vector, and decode it to a valid molecule, that is why I was looking into this repo.

**Comment by drugilsberg** [comment]
Hey @htalibart if you want to experiment with dissecting the paccmann_chemistry models, you can do this via the gt4sd interface following the recipes from some of the examples we have there:
- https://github.com/GT4SD/gt4sd-core/blob/main/notebooks/explore-molecular-generative-models-latent-spaces.ipynb
- https://github.com/GT4SD/gt4sd-core/blob/main/notebooks/visum-2022-handson-generative-models.ipynb

**Comment by htalibart** [comment]
Ok, I will look into it, thank you!

**Comment by jannisborn** [comment]
Closing this issue, but feel free to reopen, either here or directly in GT4SD in case you play with that (which I recommend too!)
