### ISSUE TITLE
Incorrect hidden layer reshaping in GRUEncoder

### ISSUE THREAD

**Issue by niladell** [PaccMann/paccmann_chemistry#5]
@drugilsberg @jannisborn I think that this reshape here is wrong, but I would like to double check with you guys:
https://github.com/PaccMann/paccmann_chemistry/blob/0ed24301db909b2dc5a15a2f7a9fda19dc36ff0a/paccmann_chemistry/models/vae.py#L79-L82

So, what I am seeing right now (and I hope I'm just doing something wrong) is that `hidden`'s batch dimension ends up being mixed up with the `n_directions` dimension, i.e. mixing the samples together.

I think that instead of what we have, the correct thing to do would be something like this:
```python
# Layers x Directions x Batch x Cell_size -> D x B x C
hidden = hidden[-1, :, :, :]

# D x B x C -> B x D x C
hidden = hidden.permute(1, 0, 2)

# B x D x C -> B x D*C
hidden = hidden.reshape(
            batch_size, cell_size * n_directions
        )
```

I made a small snippet that shows and checks what I am referring to with some dummy data: https://gist.github.com/niladell/a2bd11546ca7a4bf2c8cd9a267683f65

It's quite a quick hot-fix to push, I can do that, however I wanted to check with you first.

**Comment by drugilsberg** [comment]
@niladell thanks for reporting this. I checked quickly the material posted and I'm not super sure about the fix since I did not write this part of the code. I will have more time to look into this tomorrow so I would keep it on hold.
The part that makes me unsure is the for loop done on the sequence before the line of the code you reported.

**Comment by drugilsberg** [comment]
@niladell but it's true that a permutation seems needed to avoid mixing directions and batch up.

**Comment by niladell** [comment]
At first glance, the for loop part seemed okay to be. As I understood it, it's feeding one token at a time, so that sounds reasonable to me.

**Comment by jannisborn** [comment]
Hm, i also didn’t write this piece of code by myself. eventually it was even taken from the paper from the isayev group. I will check this tonight 

—
Jannis

**Comment by drugilsberg** [comment]
Ok I run the gist and I'm pretty much convinced the fix @niladell is proposing is correct. The for loop was perfectly fine.

**Comment by niladell** [comment]
Okay, I'll push it to `dev` this afternoon. Should I cherry pick it and make a quick hot-fix in `master` too or there's no need to rush?

**Comment by drugilsberg** [comment]
I would say `dev` is fine. It is a good occasion also to refactor a bit the code that is a bit messy. We need to retrain the molecule generator on ZINC anyhow.

**Comment by jannisborn** [comment]
I checked in a bit more detail and you are right @niladell 
Thanks a lot for reporting and fixing this, especially also for the new unit tests 👍 

We need the permutation before the reshaping. Fortunately, the encoder is not used in the conditional generator and this code snippet does not repeat in the decoder. The for loop just passes one token at a time and actually that was the workaround @oskoa came up with to get the code running with batches, I remember that the isayev paper used a batch size of 1 only :O 

I think we can start preparing a PR soon.

**Comment by niladell** [comment]
Yeah, as far as my experience goes dealing with variable length sequences can be a nightmare, and going for a batch size of 1 is definitively a bit of a crazy move—I'm glad we can batch our samples. Tho, I wonder if any of the different flavors of the [`PackedSequence`](https://pytorch.org/docs/stable/nn.html#packedsequence) could be useful here. Maybe we can check if we go for a bigger refactoring.

It does not affect the decoder directly when generating, but it definitively affects it when training it as a VAE. So, idk how reliable such a generator would be.

I agree with preparing a PR soon. For now I'll set this issue as closed, if there's anything else to discuss here we can re-open it.
