### ISSUE TITLE
Fixing bidirectionallity in the GRU

### ISSUE THREAD

**Issue by niladell** [PaccMann/paccmann_chemistry#6]
Currently our model explicitly passes the batched tokens 1-by-1 (i.e. we pass `[1, batch_size]` input each time):
https://github.com/PaccMann/paccmann_chemistry/blob/631194ea466e2198c3a065906ad926cc7014c195/paccmann_chemistry/models/vae.py#L72-L73

This explicit approach is required, as we are using a [stack with the GRU](https://papers.nips.cc/paper/5857-inferring-algorithmic-patterns-with-stack-augmented-recurrent-nets.pdf). However this method makes it such that the [GRU](https://pytorch.org/docs/stable/nn.html#gru) only sees one token at a time, making implicit bidirectional GRU useless (as it requires the entire sequence of tokens to be passed at once).

For that reason, we need to find a way to make the bidirectional GRU explicitly.

Together with @jannisborn we discussed two possible options:
- [x] Having two independent StackedGRUs—one for the forward direction and one for the backwards—and combining (e.g. concatenating) the outputs of them two.
- [ ] Having a single StackGRU running first the forward pass (storing the output), then the backward pass, and combining both outputs at the end. For this to work we would need to swap all the directional punctuation symbols. For example, if the input for the forward pass is `CCC(=O)O`, the backward pass should be `O(O=)CCC`.
  - This however could be akin to an augmentation step, so we were not sure if it would make sense to push this second option forward. 

The bidirectionallity would mostly concern the Encoding step, as the Decoding we have is an autoregresive process (so not sure how a bidirectional GRU could be implemented there, idk maybe as a sort of refinement step (tho this is probably out of the scope of this issue)).

@jannisborn feel free to add/correct this if I forgot something from our discussion.

**Comment by drugilsberg** [comment]
ticked the best option :)

**Comment by niladell** [comment]
Roger Roger

@jannisborn was very inclined for that option too!

**Comment by jannisborn** [comment]
23a560f should have fixed this. Have a look @niladell @drugilsberg 

The `StackGRUEncoder` class can now parse a `bidirectional` keyword. If `True`, a second `StackGRU` object with separate stacks will be created in the constructor. Every pass through the parent object (StackGRUEncoder`) will first compute the forward pass through the forward `StackGRU` and then revert the sequence and present it to the second `StackGRU` object (called `backward_stack_gru`.

*NOTE*: This bidirectionality option is only available for the encoder. We may attempt bidirectional decoding in a future issue (e.g. [see this paper from Gisbert's group](https://pubs.acs.org/doi/10.1021/acs.jcim.9b00943)), but for the moment, it's not supported (and honestly, I'm not convinced it's worth the effort atm).

Let's close this when we merge `dev` into `master`.

**Comment by drugilsberg** [comment]
@jannisborn
I gave it look and I agree the implementation is perfectly fine.
Decoding in a bidirectional fashion can be tricky so I agree that it's not worth the effort at the moment.
